server.port=1080
#server.servlet.contextPath=/example
server.error.include-message=always


export.dir=/opt/static-data-efs/elastic-data-backup

# Mongo
mongo.connectionString=mongodb://user:pass@localhost:27017